# Generated by Django 5.0.1 on 2024-01-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact_alter_news_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
