# Generated by Django 5.0.1 on 2024-01-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news/images'),
        ),
    ]
