# Generated by Django 5.0.1 on 2024-01-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.TextField(default='', null=True),
        ),
    ]
