# Generated by Django 5.0.1 on 2024-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
