# Generated by Django 5.0.1 on 2024-01-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
